config/routes.rb
Multiplex::Application.routes.draw do

  devise_for :users,
    :skip => [:passwords, :registrations],
    :controllers => { :registrations => "registrations" } do
    get "sign_in", :to => "devise/sessions#new"
    get "sign_out", :to => "devise/sessions#destroy"
    get "sign_up", :to => "registrations#new"
    post "user_registration", :to => "registrations#create"
    get "new_user_registration", :to => "registrations#new"
  end

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  resources :users, :only => [] do
    get 'unsubscribe', :on => :member
  end

  resources :payments, :only => [:new] do
    post 'paypal_ipn', :on => :collection, :as => :paypal_ipn
  end

  resources :messages, :only => [] do
    post 'sendgrid_create', :on => :collection
    post 'cloudmailin_create', :on => :collection
    get 'deliver', :on => :member
  end
    
  resources :delivery_manifests, :only => [:update] do
    get 'update', :on => :member
  end 

  match 'faq' => 'dashboard#faq', :as => :faq
  match 'learn_more' => 'dashboard#learn_more', :as => :learn_more
  match 'help' => 'dashboard#help', :as => :help
  match 'send_summary' => 'dashboard#send_summary', :as => :send_summary
  
  namespace 'internal' do
    resources :users, :only => [] do
      get 'test_summary_email', :on => :collection
    end
  end

  root :to => "dashboard#index"

end

app/models/delivery_manifest.rb
class DeliveryManifest < ActiveRecord::Base
  include DeliverySecret
  belongs_to :user
  has_many :manifest_entries
  has_many :messages, :through => :manifest_entries
  accepts_nested_attributes_for :manifest_entries
  
  def self.summary_for(user)
    messages = user.messages.unsummarized
    self.new(:user => user, :messages => messages)
  end

  def date_range
    start = self.messages.order("created_at ASC").first
    if start.present? 
      start = start.created_at.to_date
    else
      start = self.user.created_at.to_date
    end
    Range.new(start,Time.now.to_date)
  end
  
  def mark_as_delivered!
    messages.each do |m|
      m.update_attribute(:summarized, true)
    end
  end
end

app/controllers/delivery_manifests_controller.rb
class DeliveryManifestsController < ApplicationController
  respond_to :html
  skip_before_filter :verify_authenticity_token 

  def update
    @manifest = DeliveryManifest.find(params[:id])
    if params[:delivery_manifest][:delivery_secret] == @manifest.delivery_secret
      if @manifest.update_attributes(params[:delivery_manifest])
        if mobile_device?
          render 'delayedclose'
        else
          render 'autoclose'
        end
        return
      else
        flash[:error] = "There was an error trying to send your emails, sorry!"
      end
    else
      flash[:error] = "Error sending emails!"
    end
    redirect_to faq_path
  end
end

app/views/delivery_manifests/_form.html.haml
= form_for @manifest, :url => delivery_manifest_url(@manifest), :html => {:method => :get} do |g|
  = g.hidden_field :delivery_secret
  %div(style="width:100%; border-top: 1px solid #cdcdcd; border-bottom: 1px solid #cdcdcd;  margin-bottom: 10px; background-color: #f2fbed;")
    %table(style="border-color:#FFF; ")
      = g.fields_for :manifest_entries do |f|
        %tr
          %td(style="width:20px;")= f.check_box :marked_for_delivery
          %td(style="padding: 0px; 2px;")
            = succeed ":" do
              %b= f.object.message.from
            = f.object.message.subject

  = g.submit "Send Selected", :class => "omsubmit"

app/views/delivery_manifests/autoclose.html.haml
:javascript
  window.opener = window.opener ? window.opener : self;
  window.close();

:css
  .success {
    padding: 0.8em;
    margin-bottom: 1em;
    border: 2px solid #dddddd;
    background: #e6efc2;
    color: #264409;
    border-color: #c6d880;
  }
  
.success
  Your message(s) will be delivered shortly, you can close this window if it doesn't close itself. 

app/views/delivery_manifests/delayedclose.html.haml
:javascript
  for (var i = 0; i < 10; i++) {
    (function(i) {
      setTimeout(function() {
        var s = "";
        s += 10 - i;
        if ((10 - 1) === 1) {
          s += " second";
        } else {
          s += " seconds";
        }
        $('#time_left').html(s);
      }, i * 1000);
    })(i);
  }

  setTimeout(function() {
    window.opener = window.opener ? window.opener : self;
    window.close();
  }, 10*1000);

:css
  .success {
    padding: 0.8em;
    margin-bottom: 1em;
    border: 2px solid #dddddd;
    background: #e6efc2;
    color: #264409;
    border-color: #c6d880;
  }
  
.success
  Your message(s) will be delivered shortly! This window will close in <span id="time_left">10 seconds</span>. You can close this window yourself at any time. 

app/views/delivery_manifests/edit.html.haml
%p 
  Check the checkboxes below to deliver the messages from your otherbox.

= render 'delivery_manifests/new'