config/routes.rb
Multiplex::Application.routes.draw do

  devise_for :users,
    :skip => [:passwords, :registrations],
    :controllers => { :registrations => "registrations" } do
    get "sign_in", :to => "devise/sessions#new"
    get "sign_out", :to => "devise/sessions#destroy"
    get "sign_up", :to => "registrations#new"
    post "user_registration", :to => "registrations#create"
    get "new_user_registration", :to => "registrations#new"
  end

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  resources :users, :only => [] do
    get 'unsubscribe', :on => :member
  end

  resources :payments, :only => [:new] do
    post 'paypal_ipn', :on => :collection, :as => :paypal_ipn
  end

  resources :messages, :only => [] do
    post 'sendgrid_create', :on => :collection
    post 'cloudmailin_create', :on => :collection
    get 'deliver', :on => :member
  end
    
  resources :delivery_manifests, :only => [:update] do
    get 'update', :on => :member
  end 

  match 'faq' => 'dashboard#faq', :as => :faq
  match 'learn_more' => 'dashboard#learn_more', :as => :learn_more
  match 'help' => 'dashboard#help', :as => :help
  match 'send_summary' => 'dashboard#send_summary', :as => :send_summary
  
  namespace 'internal' do
    resources :users, :only => [] do
      get 'test_summary_email', :on => :collection
    end
  end

  root :to => "dashboard#index"

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  include ActiveMerchant::Billing::Integrations
  helper ActiveMerchant::Billing::Integrations::ActionViewHelper

  def new
  end

  def paypal_ipn
    @notify = Paypal::Notification.new(request.raw_post)
    Transaction.validate!(@notify)
    render :nothing => true
  end
end

app/views/payments/new.html.haml
- if user_signed_in?
  %h2 Congratulations!
  %p 
    You must now pay to activate your new OtherMail account.

  #diagram_many
    .icon
    Have your emails sent to:
    %br
    %b
      = current_user.mask_email
  #diagram_arrow
    .icon
  #diagram_one
    .icon
    You'll receive summaries at:
    %br
    %b
      = current_user.email
  
  %div
    Click the button below to proceed to PayPal's site to make a payment.
  = payment_service_for current_user.id, Multiplex::Application::PaypalAccount,
  :amount => 8.00, 
  :currency => 'CAD', 
  :service => :paypal do |service|
    - service.item_name "1 year of Othermail"
    - service.tax '0.00'
    - service.notify_url paypal_ipn_payments_url
    - service.return_url faq_url
    = submit_tag 'Make Payment', :class => "paypal_checkout"
- else
  %p 
    You need to sign up to make a payment. You can do that 
    %a{:href=>sign_up_url} here
    , or if you have signed up already you can pay using the link in the confirmation email you were sent.