config/routes.rb
Multiplex::Application.routes.draw do

  devise_for :users,
    :skip => [:passwords, :registrations],
    :controllers => { :registrations => "registrations" } do
    get "sign_in", :to => "devise/sessions#new"
    get "sign_out", :to => "devise/sessions#destroy"
    get "sign_up", :to => "registrations#new"
    post "user_registration", :to => "registrations#create"
    get "new_user_registration", :to => "registrations#new"
  end

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  resources :users, :only => [] do
    get 'unsubscribe', :on => :member
  end

  resources :payments, :only => [:new] do
    post 'paypal_ipn', :on => :collection, :as => :paypal_ipn
  end

  resources :messages, :only => [] do
    post 'sendgrid_create', :on => :collection
    post 'cloudmailin_create', :on => :collection
    get 'deliver', :on => :member
  end
    
  resources :delivery_manifests, :only => [:update] do
    get 'update', :on => :member
  end 

  match 'faq' => 'dashboard#faq', :as => :faq
  match 'learn_more' => 'dashboard#learn_more', :as => :learn_more
  match 'help' => 'dashboard#help', :as => :help
  match 'send_summary' => 'dashboard#send_summary', :as => :send_summary
  
  namespace 'internal' do
    resources :users, :only => [] do
      get 'test_summary_email', :on => :collection
    end
  end

  root :to => "dashboard#index"

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Othermail
    = include_stylesheets :screen, :media => 'screen, projection'
    = include_stylesheets :print, :media => 'print'
    /[if lt IE 8]
      = include_stylesheets :ie, :media => 'screen, projection'
    = include_javascripts :main
    
    = csrf_meta_tag
  %body
    #container
      %header
        .line &nbsp;
        .content
          %h1 
            %a{:href=>root_path} 
              %img(src="/images/logo.png" alt="Othermail")
          %nav
            = link_to "Learn More", learn_more_path
            |
            = link_to "FAQ", faq_path
            |
            = link_to "Twitter", "http://twitter.com/OtherMail"
            - if user_signed_in?
              -#%li= link_to "Sign Out", sign_out_path
          .clear
      .content
        - [:error, :notice, :success, :alert].select {|f| flash[f].present? }.each do |f|
          %div(class="#{f} flash")
            = flash[f]
        = yield :before_body
        .body
          = content_for?(:content) ? yield(:content) : yield

        #container_footer &nbsp;
    %footer
      %img(src="/images/inbox.png" alt="Othermail will rock your world.")

    - if Rails.env.production?
      :javascript
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-21995641-1']);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    :javascript
      var mpq = [];
      mpq.push(["init", "#{Multiplex::Application::MixpanelKey}"]);
      (function() {
      var mp = document.createElement("script"); mp.type = "text/javascript"; mp.async = true;
      mp.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + "//api.mixpanel.com/site_media/js/api/mixpanel.js";
      var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(mp, s);
      })();
        

app/views/layouts/email.html.haml
%html(style="margin: 0px; padding:0px;")
  %head
  %body(style="margin: 0px; padding:0px;")
    %style(type='text/css')= File.read(File.join(Rails.root, 'public', 'stylesheets', 'email.css'))
    .omline(style="background: url('#{path_to_image('header_border.png')}') repeat top left;")
    .omlogo
      = link_to image_tag("/images/logo.png", :alt => "Othermail", :width => 168, :height => 32), root_path
    .omcontent
      = yield
    .omfooter
      - rz = (@user || resource) rescue nil
      - if rz
        %a{:href => unsubscribe_user_url(rz, :secret => rz.delivery_secret)} Unsubscribe

app/views/layouts/email.text.erb
<%= yield %>

--

<% rz = (@user || resource) rescue nil %>
<% if rz.present? %>
Unsubscribe from all Othermail emails by visiting <%= unsubscribe_user_url(rz, :secret => rz.delivery_secret) %>
<% end %>

app/views/layouts/empty.html.haml
= yield

app/views/layouts/tagline.html.haml
- content_for :content do
  .elevator
    %h2 Deal with fewer emails. Simplify your life.
    
    %a.sign_up{:href => sign_up_path, :title => "Get Othermail"}
    
    %hr

  = yield

  .clear
    %hr
  
  .quote
    .words "With OtherMail, email alerts matter to me again"
    .person - Harry Brundage, operations director

= render :file => 'layouts/application'